// Placeholders for the search navigation bar input field

export const placeholders = [
    "Search for mouthwatering appetizers",
    "Search for epicurean delights",
    "Search for flavor-packed adventures",
    "Search for culinary treasures",
    "Search for palate-pleasing wonders",
    "Search for gastronomic marvels",
    "Search for delectable discoveries",
    "Search for savory sensations",
    "Search for mouthwatering masterpieces",
    "Search for culinary conquests",
    "Search for taste bud tantalizers",
    "Search for gourmet delights",
    "Search for flavor-filled fantasies",
    "Search for kitchen triumphs",
    "Search for delicious discoveries",
    "Search for savory delights",
    "Search for tasty temptations",
    "Search for culinary inspirations",
    "Search for palate-pleasing pleasures",
    "Search for homemade happiness",
    "Search for mouthwatering moments",
    "Search for savory surprises",
    "Search for culinary gems",
    "Search for flavor adventures",
    "Search for delectable diversions",
    "Search for taste bud adventures",
    "Search for palate-pleasing adventures",
    "Search for culinary wonders",
    "Search for taste sensations",
    "Search for epicurean wonders",
    "Search for cozy comfort foods",
    "Search for refreshing salads",
    "Search for sizzling grilling recipes",
    "Search for guilt-free healthy meals",
    "Search for comforting soups",
    "Search for quick and easy dinners",
    "Search for vegan delights",
    "Search for indulgent pasta dishes",
    "Search for exotic international cuisines",
    "Search for breakfast delights",
    "Search for comforting casseroles",
    "Search for crowd-pleasing party snacks",
    "Search for elegant dinner party menus",
    "Search for kid-friendly favorites",
    "Search for spicy sensations",
    "Search for nourishing bowls",
    "Search for festive holiday treats",
    "Search for one-pot wonders",
    "Search for budget-friendly meals",
    "Search for homemade pizza perfection",
    "Search for culinary classics",
    "Search for irresistible seafood dishes",
    "Search for hearty stews",
    "Search for refreshing smoothies",
    "Search for gluten-free options",
    "Search for creative vegetarian dishes",
    "Search for gourmet sandwich ideas",
    "Search for flavor-packed fantasies",
    "Search for culinary escapades",
    "Search for taste bud thrills",
    "Search for gourmet treasures",
    "Search for mouthwatering marvels",
    "Search for epicurean adventures",
    "Search for palate-pleasing quests",
    "Search for gastronomic wonders",
    "Search for tantalizing treats",
    "Search for delicious delicacies",
    "Search for flavor-filled delights",
    "Search for culinary discoveries",
    "Search for taste bud adventures",
    "Search for mouthwatering journeys",
    "Search for gourmet experiences",
    "Search for delectable delights",
    "Search for culinary gems",
    "Search for taste bud delights",
    "Search for palate-pleasing experiences",
    "Search for flavor-filled explorations",
    "Search for epicurean indulgences",
    "Search for culinary revelations",
    "Search for delicious diversions",
    "Search for tantalizing tastes",
    "Search for gourmet pleasures",
    "Search for mouthwatering wonders"
  ];